apiVersion: v1
kind: Service
metadata:
  name: {{ include "book-store.fullname" . }}
  labels:
    app: {{ include "book-store.name" . }}
    chart: {{ include "book-store.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.app.type }}
  ports:
  - name: elb-port
    port: {{ .Values.service.app.port }}
    protocol: TCP
    targetPort: {{ .Values.service.app.targetPort }}
  selector:
    app: {{ include "book-store.name" . }}
